lsi: false
safe: true
source: https://eversthomas.github.io/little-wing/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         /little_wing/css
  style:            :expanded
